titles:
  Eleceed: "https://www.scan-manga.com/8484-32027/Eleceed.html"
  One Piece: "https://www.scan-manga.com/391-58179/One-Piece.html"  
  Sakamoto Days: "https://www.scan-manga.com/7980-18863/Sakamoto-Days.html"
  Blue Lock: "https://www.scan-manga.com/5686-33005/Blue-Lock.html"
  Boruto Two Blue Vortex: "https://www.scan-manga.com/13265-01327/Boruto-Two-Blue-Vortex.html"
  Dandadan: "https://www.scan-manga.com/8925-72891/Dandadan.html"
  Yomi No Tsugai: "https://www.scan-manga.com/10120/Yomi-no-Tsugai.html"
  The Beginning After the End: "https://www.scan-manga.com/5560-91712/The-Beginning-After-the-End.html"
  Centuria: "https://www.scan-manga.com/14337/Centuria.html"
  Gachiakuta: "https://www.scan-manga.com/10479-64919/Gachiakuta.html"
  Ichi the Witch: "https://www.scan-manga.com/14658-26068/Ichi-the-Witch.html"
  Kagurabachi: "https://www.scan-manga.com/13349-78410/Kagurabachi.html"
  